import type { WikiPage, ExportResult, PackOptions } from "../types/page.js";
import { PageManager } from "../wiki/pages.js";

/**
 * Priority tiers for page ordering in CLAUDE.md output.
 * Lower number = higher priority.
 */
const PRIORITY_PREFIXES: Array<[string, number]> = [
  ["overview", 0],
  ["architecture", 1],
  ["conventions", 2],
  ["decisions", 3],
  ["repos/", 4],
  ["cross-repo/", 5],
  ["services/", 6],
  ["onboarding/", 7],
  ["people/", 8],
  ["manual/", 9],
];

const CHARS_PER_TOKEN = 4;

/**
 * Assemble wiki pages into a single CLAUDE.md file.
 * Respects token budget and prioritizes important pages.
 */
export function exportClaudeMd(
  pageManager: PageManager,
  options: PackOptions = { format: "claude-md" }
): ExportResult {
  const budget = options.budget ?? 100_000; // default 100k tokens
  const maxChars = budget * CHARS_PER_TOKEN;

  // Load and filter pages
  const pagePaths = pageManager.list(options.scope);
  const pages: WikiPage[] = [];

  for (const path of pagePaths) {
    // Skip meta pages
    if (path === "log.md" || path === "lint-report.md") continue;

    const page = pageManager.read(path);
    if (page) pages.push(page);
  }

  // Sort by priority
  pages.sort((a, b) => getPriority(a.path) - getPriority(b.path));

  // Build output within budget
  const sections: string[] = [];
  let totalChars = 0;
  let pagesIncluded = 0;

  // Add header
  const header = buildHeader(options);
  totalChars += header.length;
  sections.push(header);

  // Add table of contents
  const toc = buildTableOfContents(pages);
  totalChars += toc.length;
  sections.push(toc);

  // Add pages within budget
  for (const page of pages) {
    const section = formatPageSection(page);
    if (totalChars + section.length > maxChars) {
      // Try truncating this page to fit remaining budget
      const remaining = maxChars - totalChars;
      if (remaining > 200) {
        sections.push(truncateSection(page, remaining));
        pagesIncluded++;
      }
      break;
    }

    sections.push(section);
    totalChars += section.length;
    pagesIncluded++;
  }

  const content = sections.join("\n\n");

  return {
    format: "claude-md",
    content,
    tokenCount: Math.ceil(content.length / CHARS_PER_TOKEN),
    pagesIncluded,
  };
}

function buildHeader(options: PackOptions): string {
  const lines = ["# CLAUDE.md — Project Context"];
  lines.push("");
  lines.push("_Auto-generated by withctx. Do not edit manually._");
  if (options.scope) {
    lines.push(`_Scope: ${options.scope}_`);
  }
  lines.push(`_Generated: ${new Date().toISOString()}_`);
  return lines.join("\n");
}

function buildTableOfContents(pages: WikiPage[]): string {
  const lines = ["## Table of Contents", ""];
  for (const page of pages) {
    const anchor = page.path.replace(/[/.]/g, "-").replace(/-md$/, "");
    lines.push(`- [${page.title}](#${anchor})`);
  }
  return lines.join("\n");
}

function formatPageSection(page: WikiPage): string {
  const lines: string[] = [];
  const divider = "---";
  lines.push(divider);
  lines.push(`## ${page.title}`);
  lines.push(`_Path: ${page.path} | Updated: ${page.updatedAt}_`);
  lines.push("");
  lines.push(stripTitle(page.content));
  return lines.join("\n");
}

function truncateSection(page: WikiPage, maxChars: number): string {
  const header = `---\n## ${page.title}\n_Path: ${page.path} | Updated: ${page.updatedAt}_\n\n`;
  const remaining = maxChars - header.length - 50;
  if (remaining <= 0) return "";

  const body = stripTitle(page.content).slice(0, remaining);
  return header + body + "\n\n_[Truncated due to token budget]_";
}

function stripTitle(content: string): string {
  // Remove the first H1 heading since we add our own
  return content.replace(/^#\s+.+\n/, "").trimStart();
}

function getPriority(path: string): number {
  for (const [prefix, priority] of PRIORITY_PREFIXES) {
    if (path.startsWith(prefix) || path === `${prefix}.md`) {
      return priority;
    }
  }
  return 10; // default lowest priority
}
