import { Command } from "commander";
import chalk from "chalk";
import ora from "ora";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadConfig, getProjectRoot } from "../../config/loader.js";
import { CtxDirectory } from "../../storage/ctx-dir.js";
import { PageManager } from "../../wiki/pages.js";
import { createLLMFromCtxConfig } from "../../llm/index.js";
import { CostTracker } from "../../costs/tracker.js";
import { recordCall } from "../../usage/recorder.js";

const GLOSSARY_PAGE = "glossary.md";
const MAX_CONTEXT_CHARS = 50_000;

interface GlossaryOptions {
  output?: string;
  format?: string;
  update?: boolean;
}

interface GlossaryTerm {
  term: string;
  definition: string;
  category: string;
  references: string[];
}

const GLOSSARY_SYSTEM_PROMPT = `You are a technical writer extracting a glossary from project documentation.

Your task:
1. Read all the wiki pages provided as context.
2. Extract every meaningful term, acronym, project name, and domain-specific concept.
3. For each term, provide a clear, concise definition grounded ONLY in the wiki content.
4. Categorize each term into one of:
   - Acronym (abbreviations and their expansions, e.g. SLA, K8s, BFF)
   - Internal (project names, service names, team names, internal tools)
   - Technical (custom abstractions, patterns, frameworks, libraries specific to this codebase)
   - Business (domain-specific language, business processes, product terms)
5. Cite which wiki page(s) the term appears in.
6. Sort terms alphabetically within each letter group.

Output ONLY valid JSON in this exact format:
{
  "terms": [
    {
      "term": "Term Name",
      "definition": "Clear definition from the wiki content.",
      "category": "Acronym|Internal|Technical|Business",
      "references": ["page1.md", "page2.md"]
    }
  ]
}

Rules:
- Only include terms that are actually defined or meaningfully used in the wiki.
- Do not invent definitions. If the wiki doesn't explain a term clearly, note that it appears but its definition is unclear.
- Expand all acronyms when possible.
- Keep definitions to 1-2 sentences.
- Include at least one reference page for every term.`;

/**
 * Build the user prompt for glossary generation.
 */
function buildGlossaryPrompt(): string {
  return `Extract all glossary-worthy terms from the wiki content provided. Include:
- Acronyms and abbreviations (with expansions)
- Internal project names, service names, and team names
- Technical concepts specific to this codebase (custom patterns, abstractions)
- Business and domain-specific terms

Return the result as JSON following the exact schema specified in your instructions.`;
}

/**
 * Format glossary terms as markdown.
 */
function formatAsMarkdown(terms: GlossaryTerm[]): string {
  const sorted = [...terms].sort((a, b) =>
    a.term.toLowerCase().localeCompare(b.term.toLowerCase())
  );

  const date = new Date().toISOString().slice(0, 10);
  const lines: string[] = [
    "# Project Glossary",
    "",
    `> Auto-generated by withctx from your project wiki.`,
    `> Last updated: ${date}`,
    "",
  ];

  // Group by first letter
  let currentLetter = "";
  for (const entry of sorted) {
    const letter = entry.term[0].toUpperCase();
    if (letter !== currentLetter) {
      currentLetter = letter;
      lines.push(`## ${currentLetter}`, "");
    }

    const categoryTag =
      entry.category !== "Internal" ? ` _(${entry.category})_` : "";
    const refs =
      entry.references.length > 0
        ? ` See ${entry.references.map((r) => `[${r}](./${r})`).join(", ")}.`
        : "";

    lines.push(
      `**${entry.term}**${categoryTag} — ${entry.definition}${refs}`,
      ""
    );
  }

  return lines.join("\n");
}

/**
 * Format glossary terms as JSON.
 */
function formatAsJson(terms: GlossaryTerm[]): string {
  return JSON.stringify({ terms }, null, 2);
}

/**
 * Display glossary content in the terminal with colored formatting.
 */
function displayGlossary(content: string): void {
  const lines = content.split("\n");

  for (const line of lines) {
    if (line.startsWith("# ")) {
      console.log(chalk.bold.white(line));
    } else if (line.startsWith("## ")) {
      console.log(chalk.bold.yellow(line));
    } else if (line.startsWith("> ")) {
      console.log(chalk.dim(line));
    } else if (line.startsWith("**")) {
      // Highlight term names
      const match = line.match(/^\*\*([^*]+)\*\*/);
      if (match) {
        const rest = line.slice(match[0].length);
        console.log(chalk.bold.cyan(match[0]) + rest);
      } else {
        console.log(line);
      }
    } else {
      console.log(line);
    }
  }
}

/**
 * Parse Claude's JSON response into glossary terms.
 */
function parseGlossaryResponse(content: string): GlossaryTerm[] {
  // Strip markdown code fences if present
  const cleaned = content
    .replace(/^```(?:json)?\s*\n?/m, "")
    .replace(/\n?```\s*$/m, "")
    .trim();

  const parsed = JSON.parse(cleaned) as { terms: GlossaryTerm[] };

  if (!Array.isArray(parsed.terms)) {
    throw new Error("Invalid glossary response: missing 'terms' array");
  }

  return parsed.terms;
}

/**
 * Append an entry to the wiki log.
 */
function appendLog(pageManager: PageManager, detail: string): void {
  const logContent = pageManager.read("log.md");
  if (logContent) {
    const timestamp = new Date().toISOString();
    const newLine = `| ${timestamp} | glossary | ${detail} |`;
    const updated = logContent.content + "\n" + newLine;
    pageManager.write("log.md", updated);
  }
}

/**
 * Update index.md to include a link to glossary.md if not already present.
 */
function updateIndex(pageManager: PageManager): void {
  const indexPage = pageManager.read("index.md");
  if (!indexPage) return;

  if (indexPage.content.includes("glossary.md")) return;

  const glossaryLink = "\n- [Project Glossary](glossary.md)\n";
  const content = indexPage.content;

  const headingEnd = content.indexOf("\n\n");
  if (headingEnd !== -1) {
    const updated =
      content.slice(0, headingEnd) +
      "\n" +
      glossaryLink +
      content.slice(headingEnd);
    pageManager.write("index.md", updated);
  } else {
    pageManager.write("index.md", content + glossaryLink);
  }
}

export function registerGlossaryCommand(program: Command): void {
  program
    .command("glossary")
    .description(
      "Auto-generate a project glossary — acronyms, internal terms, and domain language from your wiki"
    )
    .option("--output <path>", "Write glossary to a file path")
    .option(
      "--format <fmt>",
      "Output format: md (default) or json",
      "md"
    )
    .option(
      "--update",
      "Write/update the glossary in .ctx/wiki/glossary.md"
    )
    .action(async (options: GlossaryOptions) => {
      const spinner = ora("Loading wiki context...").start();

      try {
        const config = loadConfig();
        const projectRoot = getProjectRoot();
        const ctxDir = new CtxDirectory(projectRoot);

        if (!ctxDir.exists()) {
          spinner.fail(
            chalk.red("No .ctx/ directory found. Run 'ctx setup' first.")
          );
          process.exit(1);
        }

        const pageManager = new PageManager(ctxDir);
        const pages = pageManager.list();

        if (pages.length === 0) {
          spinner.fail(
            chalk.red(
              "No wiki pages found. Run 'ctx ingest' to compile your context first."
            )
          );
          process.exit(1);
        }

        // Load wiki pages, respecting the character cap
        spinner.text = `Loading ${pages.length} wiki pages...`;
        const contextFiles: Array<{ path: string; content: string }> = [];
        let totalChars = 0;

        for (const pagePath of pages) {
          if (pagePath === "log.md" || pagePath === GLOSSARY_PAGE) continue;

          const page = pageManager.read(pagePath);
          if (!page) continue;

          if (totalChars + page.content.length > MAX_CONTEXT_CHARS) {
            // Truncate remaining content to fit within budget
            const remaining = MAX_CONTEXT_CHARS - totalChars;
            if (remaining > 500) {
              contextFiles.push({
                path: pagePath,
                content: page.content.slice(0, remaining),
              });
            }
            break;
          }

          contextFiles.push({ path: pagePath, content: page.content });
          totalChars += page.content.length;
        }

        if (contextFiles.length === 0) {
          spinner.fail(
            chalk.red("No usable wiki pages found after filtering.")
          );
          process.exit(1);
        }

        // Generate glossary via Claude
        spinner.text = `Extracting glossary from ${contextFiles.length} wiki pages...`;

        const claude = createLLMFromCtxConfig(config, "glossary");
        const costTracker = new CostTracker(ctxDir, {
          budget: config.costs?.budget,
          alertAt: config.costs?.alert_at,
        });

        const userPrompt = buildGlossaryPrompt();

        const response = await claude.promptWithFiles(
          userPrompt,
          contextFiles,
          {
            systemPrompt: GLOSSARY_SYSTEM_PROMPT,
            maxTokens: 8192,
            cacheSystemPrompt: true,
          }
        );

        // Parse the JSON response
        spinner.text = "Formatting glossary...";
        const terms = parseGlossaryResponse(response.content);

        // Format output
        const format = options.format ?? "md";
        const isJson = format === "json";
        const formatted = isJson
          ? formatAsJson(terms)
          : formatAsMarkdown(terms);

        // Track costs
        if (response.tokensUsed) {
          const glossaryModel = response.model ?? config.costs?.model ?? "claude-sonnet-4";
          costTracker.record(
            "glossary",
            {
              inputTokens: response.tokensUsed.input,
              outputTokens: response.tokensUsed.output,
            },
            glossaryModel
          );
          recordCall(ctxDir, "glossary", glossaryModel, {
            input: response.tokensUsed.input,
            output: response.tokensUsed.output,
            cacheRead: response.tokensUsed.cacheRead ?? 0,
            cacheWrite: response.tokensUsed.cacheCreation ?? 0,
          });
        }

        // Save to wiki if --update
        if (options.update) {
          const markdownContent = isJson
            ? formatAsMarkdown(terms)
            : formatted;
          pageManager.write(GLOSSARY_PAGE, markdownContent);
          updateIndex(pageManager);
          appendLog(
            pageManager,
            `Generated glossary with ${terms.length} terms from ${contextFiles.length} pages`
          );
        }

        // Write to output file if --output
        if (options.output) {
          const outputPath = resolve(process.cwd(), options.output);
          writeFileSync(outputPath, formatted, "utf-8");
        }

        spinner.stop();

        // Display the glossary
        console.log();
        if (isJson) {
          console.log(formatted);
        } else {
          displayGlossary(formatted);
        }
        console.log();

        // Summary
        console.log(
          chalk.green(`Glossary: ${terms.length} terms extracted`)
        );
        if (options.update) {
          console.log(
            chalk.green(`Saved to .ctx/context/${GLOSSARY_PAGE}`)
          );
        }
        if (options.output) {
          console.log(
            chalk.green(
              `Written to ${resolve(process.cwd(), options.output)}`
            )
          );
        }

        if (response.tokensUsed) {
          const total =
            response.tokensUsed.input + response.tokensUsed.output;
          console.log(
            chalk.dim(
              `Tokens: ${total.toLocaleString()} (${response.tokensUsed.input.toLocaleString()} in / ${response.tokensUsed.output.toLocaleString()} out)`
            )
          );
        }

        console.log(
          chalk.dim(
            `Generated from ${contextFiles.length} wiki page(s)`
          )
        );
      } catch (error) {
        spinner.fail(chalk.red("Glossary generation failed"));
        if (error instanceof Error) {
          console.error(chalk.red(`  ${error.message}`));
        }
        process.exit(1);
      }
    });
}
