import { Command } from "commander";
import chalk from "chalk";
import ora from "ora";
import { loadConfig, getProjectRoot } from "../../config/loader.js";
import { CtxDirectory } from "../../storage/ctx-dir.js";
import { PageManager } from "../../wiki/pages.js";
import { ClaudeClient } from "../../claude/client.js";

interface OnboardOptions {
  regenerate?: boolean;
}

export function registerOnboardCommand(program: Command): void {
  program
    .command("onboard")
    .description("Generate or display an onboarding guide from the wiki")
    .argument("[repo]", "Specific repo to generate onboarding for")
    .option("--regenerate", "Regenerate the guide even if one exists")
    .action(async (repo: string | undefined, options: OnboardOptions) => {
      const spinner = ora("Preparing onboarding guide...").start();

      try {
        const config = loadConfig();
        const projectRoot = getProjectRoot();
        const ctxDir = new CtxDirectory(projectRoot);

        if (!ctxDir.exists()) {
          spinner.fail(chalk.red("No .ctx/ directory found. Run 'ctx init' first."));
          process.exit(1);
        }

        const pageManager = new PageManager(ctxDir);

        // Determine the guide path
        const guidePath = repo
          ? `onboarding/by-repo/${repo}.md`
          : "onboarding/guide.md";

        // Check if guide already exists
        const existingGuide = pageManager.read(guidePath);
        if (existingGuide && !options.regenerate) {
          spinner.stop();
          console.log();
          console.log(chalk.bold.cyan("Onboarding Guide"));
          console.log(chalk.dim("─".repeat(50)));
          console.log();
          console.log(existingGuide.content);
          console.log();
          console.log(chalk.dim(`Guide location: .ctx/context/${guidePath}`));
          console.log(chalk.dim("Run with --regenerate to refresh."));
          return;
        }

        // Load wiki pages for context
        const allPages = pageManager.list();
        if (allPages.length <= 1) {
          spinner.fail(chalk.red("Not enough wiki content. Run 'ctx ingest' first."));
          process.exit(1);
        }

        const contextFiles: Array<{ path: string; content: string }> = [];
        for (const pagePath of allPages) {
          if (pagePath === "log.md") continue;
          const page = pageManager.read(pagePath);
          if (page) {
            // If repo-specific, prioritize repo pages
            if (repo) {
              if (
                pagePath.includes(repo) ||
                pagePath.startsWith("repos/") ||
                pagePath === "index.md" ||
                pagePath.startsWith("cross-repo/") ||
                pagePath.startsWith("services/")
              ) {
                contextFiles.push({ path: pagePath, content: page.content });
              }
            } else {
              contextFiles.push({ path: pagePath, content: page.content });
            }
          }
        }

        // Generate with Claude
        spinner.text = "Generating onboarding guide with Claude...";

        const claude = new ClaudeClient(config.costs?.model ?? "claude-sonnet-4");
        const available = await claude.isAvailable();
        if (!available) {
          spinner.fail(chalk.red("Claude CLI not found."));
          process.exit(1);
        }

        const scopeLabel = repo ? `the ${repo} repository` : `the ${config.project} project`;
        const prompt = `Generate a comprehensive onboarding guide for a new developer joining ${scopeLabel}.

## The guide should include:
1. **Project Overview** — What this project does, its purpose
2. **Architecture** — High-level system architecture, key components
3. **Getting Started** — Setup instructions, prerequisites, how to run locally
4. **Key Concepts** — Important domain concepts and terminology
5. **Codebase Navigation** — Where to find things, important directories
6. **Development Workflow** — How to make changes, PR process, testing
7. **Common Tasks** — Frequent operations a developer would need to do
8. **Who to Ask** — Key people/teams (if mentioned in the wiki)
9. **Gotchas** — Common pitfalls and things to watch out for

Base the guide ENTIRELY on the wiki content provided. If information is missing for a section, note what's unknown and suggest the developer ask about it.`;

        const response = await claude.promptWithFiles(prompt, contextFiles, {
          systemPrompt:
            "You are an onboarding guide creator. Build a helpful, practical guide from the wiki content. Be specific, not generic.",
        });

        // Save the guide
        const guideContent = `# Onboarding Guide${repo ? ` — ${repo}` : ""}

_Auto-generated by withctx on ${new Date().toISOString()}_

${response.content}
`;

        pageManager.write(guidePath, guideContent);

        spinner.stop();

        // Display the guide
        console.log();
        console.log(chalk.bold.cyan("Onboarding Guide"));
        console.log(chalk.dim("─".repeat(50)));
        console.log();
        console.log(guideContent);
        console.log();
        console.log(chalk.dim(`Saved to .ctx/context/${guidePath}`));
      } catch (error) {
        spinner.fail(chalk.red("Onboarding guide generation failed"));
        if (error instanceof Error) {
          console.error(chalk.red(`  ${error.message}`));
        }
        process.exit(1);
      }
    });
}
