import { Command } from "commander";
import chalk from "chalk";
import ora from "ora";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadConfig, getProjectRoot } from "../../config/loader.js";
import { CtxDirectory } from "../../storage/ctx-dir.js";
import { PageManager } from "../../wiki/pages.js";
import { ClaudeClient } from "../../claude/client.js";
import type { PackOptions } from "../../types/page.js";

interface PackCliOptions {
  format?: "claude-md" | "system-prompt" | "markdown";
  scope?: string;
  query?: string;
  output?: string;
  budget?: string;
}

function estimateTokens(text: string): number {
  // Rough estimate: ~4 chars per token
  return Math.ceil(text.length / 4);
}

function packClaudeMd(
  projectName: string,
  pages: Array<{ path: string; content: string }>
): string {
  let output = `# CLAUDE.md — ${projectName}\n\n`;
  output += `_Auto-generated by withctx. ${pages.length} pages compiled._\n\n`;
  output += `---\n\n`;

  for (const page of pages) {
    output += `${page.content}\n\n---\n\n`;
  }

  return output;
}

function packSystemPrompt(
  projectName: string,
  pages: Array<{ path: string; content: string }>
): string {
  let output = `You have access to the following project context for "${projectName}":\n\n`;

  for (const page of pages) {
    output += `<context file="${page.path}">\n${page.content}\n</context>\n\n`;
  }

  output += `Use this context to answer questions accurately. Cite sources when possible.\n`;

  return output;
}

function packMarkdown(
  projectName: string,
  pages: Array<{ path: string; content: string }>
): string {
  let output = `# ${projectName} — Context Wiki\n\n`;
  output += `## Table of Contents\n\n`;

  for (const page of pages) {
    const title = page.content.match(/^#\s+(.+)$/m)?.[1] ?? page.path;
    output += `- [${title}](#${page.path.replace(/[/.]/g, "-")})\n`;
  }

  output += `\n---\n\n`;

  for (const page of pages) {
    output += `<a id="${page.path.replace(/[/.]/g, "-")}"></a>\n\n`;
    output += `${page.content}\n\n---\n\n`;
  }

  return output;
}

export function registerPackCommand(program: Command): void {
  program
    .command("pack")
    .description("Assemble wiki pages into a single output (CLAUDE.md, system-prompt, etc.)")
    .option("--format <fmt>", "Output format: claude-md, system-prompt, markdown", "claude-md")
    .option("--scope <dir>", "Limit to a specific wiki subdirectory")
    .option("--query <q>", "Focus output on pages relevant to a query")
    .option("--output <path>", "Write output to file instead of stdout")
    .option("--budget <tokens>", "Token budget limit")
    .action(async (options: PackCliOptions) => {
      const spinner = ora("Packing wiki...").start();

      try {
        const config = loadConfig();
        const projectRoot = getProjectRoot();
        const ctxDir = new CtxDirectory(projectRoot);

        if (!ctxDir.exists()) {
          spinner.fail(chalk.red("No .ctx/ directory found. Run 'ctx init' first."));
          process.exit(1);
        }

        const pageManager = new PageManager(ctxDir);
        const allPagePaths = pageManager.list(options.scope);

        if (allPagePaths.length === 0) {
          spinner.fail(chalk.red("No wiki pages found."));
          process.exit(1);
        }

        // Load all pages
        let pages: Array<{ path: string; content: string }> = [];
        for (const pagePath of allPagePaths) {
          if (pagePath === "log.md") continue; // Skip log from pack output
          const page = pageManager.read(pagePath);
          if (page) {
            pages.push({ path: pagePath, content: page.content });
          }
        }

        // If query-focused, use Claude to rank relevance
        if (options.query) {
          spinner.text = "Ranking pages by relevance...";
          const claude = new ClaudeClient(config.costs?.model ?? "claude-sonnet-4", { baseURL: config.ai?.base_url });
          const available = await claude.isAvailable();

          if (available) {
            const pageList = pages.map((p) => p.path).join("\n");
            const rankPrompt = `Given this query: "${options.query}"

Rank these wiki pages by relevance (most relevant first). Output just the filenames, one per line:
${pageList}`;

            try {
              const response = await claude.prompt(rankPrompt, {
                systemPrompt: "Rank the pages. Output only filenames, one per line, most relevant first.",
              });

              const rankedPaths = response.content
                .trim()
                .split("\n")
                .map((l) => l.trim())
                .filter(Boolean);

              const pageMap = new Map(pages.map((p) => [p.path, p]));
              const reordered: typeof pages = [];

              for (const rp of rankedPaths) {
                const found = pageMap.get(rp);
                if (found) reordered.push(found);
              }

              // Add any pages not in the ranked list
              for (const p of pages) {
                if (!reordered.find((r) => r.path === p.path)) {
                  reordered.push(p);
                }
              }

              pages = reordered;
            } catch {
              // Fall back to original order
            }
          }
        }

        // Apply token budget
        const budget = options.budget ? parseInt(options.budget, 10) : undefined;
        if (budget) {
          const budgeted: typeof pages = [];
          let currentTokens = 0;

          for (const page of pages) {
            const pageTokens = estimateTokens(page.content);
            if (currentTokens + pageTokens > budget) break;
            budgeted.push(page);
            currentTokens += pageTokens;
          }

          if (budgeted.length < pages.length) {
            spinner.info(
              chalk.yellow(
                `Budget limit: including ${budgeted.length} of ${pages.length} pages (~${currentTokens} tokens)`
              )
            );
          }
          pages = budgeted;
        }

        // Generate output based on format
        const format = (options.format ?? "claude-md") as PackOptions["format"];
        let output: string;

        switch (format) {
          case "system-prompt":
            output = packSystemPrompt(config.project, pages);
            break;
          case "markdown":
            output = packMarkdown(config.project, pages);
            break;
          case "claude-md":
          default:
            output = packClaudeMd(config.project, pages);
            break;
        }

        spinner.stop();

        const tokenCount = estimateTokens(output);

        // Output
        if (options.output) {
          const outputPath = resolve(options.output);
          writeFileSync(outputPath, output);
          console.log(
            chalk.green(
              `Packed ${pages.length} pages into ${chalk.bold(outputPath)} (~${tokenCount} tokens)`
            )
          );
        } else {
          console.log(output);
          console.error(
            chalk.dim(
              `\n--- ${pages.length} pages, ~${tokenCount} tokens, format: ${format} ---`
            )
          );
        }
      } catch (error) {
        spinner.fail(chalk.red("Pack failed"));
        if (error instanceof Error) {
          console.error(chalk.red(`  ${error.message}`));
        }
        process.exit(1);
      }
    });
}
