import { Command } from "commander";
import chalk from "chalk";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { basename, join, resolve } from "node:path";
import { parse as parseYaml, stringify as yamlStringify } from "yaml";
import {
  readReposFromPaths,
  parseReposFile,
  scanForRepos,
  type DetectedRepo,
} from "../../setup/scan-repos.js";
import type { CtxConfig } from "../../types/config.js";
import { writeSecretFile } from "../../security/fs-modes.js";

/**
 * `ctx publish` — scaffold a CI-refreshed wiki.
 *
 * Two modes, auto-detected from where the command runs:
 *
 *   Topology A (in-place):
 *     Run from inside a single git repo that already is the "thing the
 *     wiki describes" (no name arg needed). The command drops a refresh
 *     workflow into `.github/workflows/refresh-wiki.yml`, marks the
 *     existing `ctx.yaml` as `refreshed_by: ci`, and prints the secrets
 *     you need to set. No new repo is created. One repo, one wiki, one
 *     source of truth.
 *
 *   Topology B (wiki host repo):
 *     Run from a parent folder that is NOT a git repo, with a name arg
 *     (`ctx publish lsp-ctx`). The command creates `./lsp-ctx/` as a
 *     fresh git repo containing ctx.yaml + a workflow that checks out
 *     the sibling source repos before compiling. Use this when the
 *     wiki aggregates across N repos and none of them "owns" it.
 *
 * Either mode writes `refreshed_by: ci` into the yaml, which the
 * guardrail in src/config/refresh-policy.ts uses to block local
 * refreshes by default — preventing every developer on the team from
 * burning LLM budget on a rebuild nobody asked for.
 */

interface PublishOptions {
  /** Explicit repo paths for Topology B (same semantics as `ctx setup --repo`). */
  repo?: string[];
  /** Repo manifest file (same semantics as `ctx setup --repos-file`). */
  reposFile?: string;
  /** Cron schedule for the refresh workflow. Default: every 6 hours. */
  schedule?: string;
  /** Skip the "are you sure?" confirmations. */
  yes?: boolean;
  /** Replace an existing workflow file if one is already there. */
  force?: boolean;
}

// ---------------------------------------------------------------------------
// Workflow templates
// ---------------------------------------------------------------------------
// We write these as literal strings rather than pulling from a template
// file because (a) the scaffold is the user's first impression of the
// feature, and (b) a single embedded template is easier to audit than
// a separate asset file that ships with the npm package.

function workflowInPlace(schedule: string): string {
  return `# Generated by \`ctx publish\` — the refresh workflow for this wiki.
#
# This workflow rebuilds the withctx wiki in CI so every developer on
# the team gets the same answers without having to run ingest locally.
# See \`refreshed_by: ci\` in ctx.yaml — that flag blocks local refresh
# unless you explicitly pass --allow-local-refresh on the command line.
#
# Required repo secrets:
#   ANTHROPIC_API_KEY  — the Claude key used to compile the wiki
#
# Edit the schedule below if every 6 hours is too often or not often
# enough. The first run after you push this file will seed the wiki.
name: refresh-wiki

on:
  push:
    branches: [main]
    paths-ignore:
      - '.ctx/**'       # don't loop on our own commits
      - '**/*.md'
  schedule:
    - cron: "${schedule}"
  workflow_dispatch: {}

permissions:
  contents: write       # needed to commit the refreshed .ctx/ back

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # git history used for churn + hotspots

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install withctx
        run: npm i -g withctx

      - name: Refresh wiki
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
        # --allow-local-refresh: CI is the authorised refresher, so we
        # explicitly opt past the refreshed_by: ci guardrail here.
        run: ctx sync --allow-local-refresh

      - name: Commit refreshed wiki
        run: |
          git config user.name "ctx-bot"
          git config user.email "ctx-bot@users.noreply.github.com"
          git add .ctx/
          if git diff --cached --quiet; then
            echo "No wiki changes to commit."
          else
            git commit -m "chore(wiki): refresh $(date -u +%Y-%m-%d)"
            git push
          fi
`;
}

function workflowHostRepo(
  schedule: string,
  repos: Array<{ name: string; github: string; branch?: string }>
): string {
  // For the wiki-host pattern we need to check out every source repo
  // into a sibling path so `ctx.yaml`'s relative `../lsp-web`-style
  // paths resolve correctly at compile time.
  const checkoutSteps = repos
    .map((r) => {
      // Strip https://github.com/ prefix to get owner/repo for the
      // actions/checkout `repository` input, which wants that shape.
      const slug = r.github
        .replace(/^https?:\/\//, "")
        .replace(/^github\.com\//, "");
      const branchLine = r.branch ? `          ref: ${r.branch}\n` : "";
      return `      - name: Check out ${r.name}
        uses: actions/checkout@v4
        with:
          repository: ${slug}
          path: ../${r.name}
${branchLine}          token: \${{ secrets.SOURCE_REPO_TOKEN }}`;
    })
    .join("\n\n");

  return `# Generated by \`ctx publish\` — the refresh workflow for this wiki
# host repo. This repo holds ONLY the compiled wiki; the source code
# lives in ${repos.length} sibling repo(s) that this workflow checks out
# before compiling.
#
# Required repo secrets:
#   ANTHROPIC_API_KEY  — Claude key used to compile the wiki
#   SOURCE_REPO_TOKEN  — PAT or GitHub App token with read access to
#                        the source repos (needs \`contents: read\`)
name: refresh-wiki

on:
  schedule:
    - cron: "${schedule}"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this wiki repo
        uses: actions/checkout@v4
        with:
          path: wiki

${checkoutSteps}

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install withctx
        run: npm i -g withctx

      - name: Refresh wiki
        working-directory: wiki
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
        # --allow-local-refresh: CI is the authorised refresher, so we
        # explicitly opt past the refreshed_by: ci guardrail here.
        run: ctx sync --allow-local-refresh

      - name: Commit refreshed wiki
        working-directory: wiki
        run: |
          git config user.name "ctx-bot"
          git config user.email "ctx-bot@users.noreply.github.com"
          git add .ctx/
          if git diff --cached --quiet; then
            echo "No wiki changes to commit."
          else
            git commit -m "chore(wiki): refresh $(date -u +%Y-%m-%d)"
            git push
          fi
`;
}

// In-place publish deliberately does NOT drop a README — the repo
// already has one and we don't want to clobber it. The workflow file
// and ctx.yaml comments carry the documentation.

function readmeHostRepo(
  projectName: string,
  repos: Array<{ name: string; github: string }>
): string {
  const list = repos.map((r) => `- \`${r.name}\` — ${r.github}`).join("\n");
  return `# ${projectName} — shared withctx wiki

This repo holds a [withctx](https://github.com/imamchishty/withctx) wiki
that aggregates across ${repos.length} source repo(s):

${list}

The compiled markdown lives under \`.ctx/context/\` and is refreshed by
CI every few hours.

## Read the wiki

\`\`\`bash
git clone <this-repo>
cd ${projectName}
ctx chat
\`\`\`

## Do **not** run \`ctx ingest\` or \`ctx sync\` locally

This wiki is marked \`refreshed_by: ci\`. Those commands are blocked for
per-developer runs — pass \`--allow-local-refresh\` if you really need a
local rebuild.

## Workflow secrets

- \`ANTHROPIC_API_KEY\` — Claude key used to compile the wiki.
- \`SOURCE_REPO_TOKEN\` — PAT / GitHub App token with read access to
  the source repos above.
`;
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

function normaliseCronSchedule(schedule: string | undefined): string {
  // Default: every 6 hours on the hour. Cheap enough for most wikis,
  // frequent enough that devs don't see stale answers.
  return (schedule ?? "0 */6 * * *").trim();
}

/**
 * Resolve the list of source repos for Topology B, same priority as
 * `ctx setup`: --repo beats --repos-file beats auto-scan of cwd.
 */
function resolveSourceRepos(
  cwd: string,
  options: PublishOptions
): DetectedRepo[] {
  const explicit: string[] = [];
  if (options.repo && options.repo.length > 0) {
    explicit.push(...options.repo);
  }
  if (options.reposFile) {
    const filePath = resolve(cwd, options.reposFile);
    explicit.push(...parseReposFile(filePath));
  }

  if (explicit.length > 0) {
    const { repos, missing } = readReposFromPaths(explicit, cwd, cwd);
    if (missing.length > 0) {
      console.log(
        chalk.yellow(`  Skipped ${missing.length} path(s) that aren't git repos:`)
      );
      for (const m of missing) console.log(chalk.dim(`    ${m}`));
      console.log();
    }
    return repos;
  }

  // Fall back to sibling auto-scan.
  return scanForRepos(cwd);
}

function isInPlaceMode(cwd: string, nameArg: string | undefined): boolean {
  // In-place: we're inside a git repo that already has a ctx.yaml,
  // and the user didn't pass a name (no new repo to create).
  const hasGit = existsSync(join(cwd, ".git"));
  const hasConfig = existsSync(join(cwd, "ctx.yaml"));
  return hasGit && hasConfig && !nameArg;
}

// ---------------------------------------------------------------------------
// Topology A: in-place publish
// ---------------------------------------------------------------------------

function publishInPlace(cwd: string, options: PublishOptions): void {
  const configPath = join(cwd, "ctx.yaml");

  // Load and mark as CI-refreshed. Preserve every other field the user
  // may have hand-edited — we only touch `refreshed_by`.
  const raw = readFileSync(configPath, "utf-8");
  const parsed = parseYaml(raw) as Partial<CtxConfig> & Record<string, unknown>;

  if (parsed.refreshed_by === "ci") {
    console.log(
      chalk.dim("  ctx.yaml is already marked refreshed_by: ci — good.")
    );
  } else {
    parsed.refreshed_by = "ci";
    writeSecretFile(configPath, yamlStringify(parsed, { lineWidth: 120 }));
    console.log(
      chalk.green("  ✓") +
        " Set " +
        chalk.cyan("refreshed_by: ci") +
        " in ctx.yaml"
    );
  }

  // Drop the workflow file.
  const workflowDir = join(cwd, ".github", "workflows");
  const workflowPath = join(workflowDir, "refresh-wiki.yml");

  if (existsSync(workflowPath) && options.force !== true) {
    console.log();
    console.log(
      chalk.yellow("  ⚠ ") +
        ".github/workflows/refresh-wiki.yml already exists — skipping."
    );
    console.log(
      chalk.dim("    Pass --force to overwrite, or edit the file by hand.")
    );
  } else {
    mkdirSync(workflowDir, { recursive: true });
    writeFileSync(
      workflowPath,
      workflowInPlace(normaliseCronSchedule(options.schedule))
    );
    console.log(
      chalk.green("  ✓") + " Wrote .github/workflows/refresh-wiki.yml"
    );
  }

  // Print next-steps.
  const projectName = (parsed.project as string | undefined) ?? basename(cwd);
  console.log();
  console.log(chalk.bold.green("  Published!") + chalk.dim(` ${projectName}`));
  console.log();
  console.log(chalk.bold("  Next steps:"));
  console.log();
  console.log(
    `    ${chalk.cyan("1.")} Add the Anthropic key as a repo secret:`
  );
  console.log(
    `       ${chalk.bold("gh secret set ANTHROPIC_API_KEY --body \"$ANTHROPIC_API_KEY\"")}`
  );
  console.log();
  console.log(`    ${chalk.cyan("2.")} Commit and push:`);
  console.log(
    `       ${chalk.bold("git add ctx.yaml .github/workflows/refresh-wiki.yml")}`
  );
  console.log(`       ${chalk.bold('git commit -m "Add self-refreshing wiki"')}`);
  console.log(`       ${chalk.bold("git push")}`);
  console.log();
  console.log(
    `    ${chalk.cyan("3.")} Watch the first run under the ${chalk.bold("Actions")} tab.`
  );
  console.log();
  console.log(
    chalk.dim(
      "  Local ingest/sync is now blocked for this wiki (refreshed_by: ci)."
    )
  );
  console.log(
    chalk.dim("  To override in an emergency: ") +
      chalk.bold("ctx sync --allow-local-refresh")
  );
  console.log();
}

// ---------------------------------------------------------------------------
// Topology B: wiki host repo
// ---------------------------------------------------------------------------

function publishHostRepo(
  cwd: string,
  name: string,
  options: PublishOptions
): void {
  const targetDir = resolve(cwd, name);

  // Safety: don't clobber an existing non-empty folder.
  if (existsSync(targetDir)) {
    const contents = (() => {
      try {
        return readdirSync(targetDir);
      } catch {
        return [];
      }
    })();
    const nonEmpty = contents.filter((f) => f !== ".DS_Store");
    if (nonEmpty.length > 0) {
      console.error();
      console.error(
        chalk.red(`  ./${name}/ already exists and isn't empty.`)
      );
      console.error();
      console.error(
        chalk.dim(
          "  If it's already a withctx wiki, use `ctx publish --update` from inside it."
        )
      );
      console.error(
        chalk.dim("  Otherwise pick a different name or remove the folder.")
      );
      console.error();
      process.exit(1);
    }
  }

  // Resolve source repos (explicit --repo/--repos-file or sibling scan).
  console.log(chalk.bold("  Discovering source repos..."));
  const detected = resolveSourceRepos(cwd, options);

  if (detected.length === 0) {
    console.error();
    console.error(
      chalk.red(
        "  No source repos found. Either run from a workspace folder with"
      )
    );
    console.error(
      chalk.red(
        "  sibling git repos, or pass --repo <path...> with explicit paths."
      )
    );
    console.error();
    process.exit(1);
  }

  const withRemotes = detected.filter((r) => r.github !== null);
  if (withRemotes.length === 0) {
    console.error();
    console.error(
      chalk.red(
        "  None of the discovered repos have a GitHub origin remote."
      )
    );
    console.error(
      chalk.dim(
        "  A CI workflow needs remote URLs so it can check repos out. Add remotes"
      )
    );
    console.error(
      chalk.dim("  and re-run, or use `ctx setup` for a local-only wiki.")
    );
    console.error();
    process.exit(1);
  }

  console.log();
  console.log(chalk.bold(`  Will add ${withRemotes.length} source repo(s):`));
  for (const r of withRemotes) {
    const branch = r.branch ? chalk.dim(` [${r.branch}]`) : "";
    console.log(
      `    ${chalk.cyan(r.name.padEnd(20))} ${chalk.dim(r.github!)}${branch}`
    );
  }
  if (detected.length > withRemotes.length) {
    const skipped = detected.length - withRemotes.length;
    console.log(
      chalk.dim(`    (${skipped} local-only repo(s) skipped — no origin remote)`)
    );
  }
  console.log();

  // Build the wiki host's ctx.yaml. Paths in sources.local[] point at
  // the sibling source repos relative to the wiki dir (../lsp-web etc).
  const config: CtxConfig = {
    project: name,
    refreshed_by: "ci",
    repos: withRemotes.map((r) => {
      const entry: { name: string; github: string; branch?: string } = {
        name: r.name,
        github: r.github!,
      };
      if (r.branch) entry.branch = r.branch;
      return entry;
    }),
    sources: {
      local: withRemotes.map((r) => ({
        name: r.name,
        // Relative to ctx.yaml, which lives inside targetDir. The
        // sibling source repos live one level up.
        path: `../${r.name}`,
      })),
    },
    ai: {
      provider: "anthropic",
      api_key: "${ANTHROPIC_API_KEY}",
    },
    costs: {
      budget: 10,
      alert_at: 80,
      model: "claude-sonnet-4",
    },
  };

  // Create the directory tree and drop files.
  mkdirSync(join(targetDir, ".github", "workflows"), { recursive: true });

  writeSecretFile(
    join(targetDir, "ctx.yaml"),
    yamlStringify(config, { lineWidth: 120 })
  );
  writeFileSync(
    join(targetDir, ".github", "workflows", "refresh-wiki.yml"),
    workflowHostRepo(
      normaliseCronSchedule(options.schedule),
      withRemotes.map((r) => ({
        name: r.name,
        github: r.github!,
        ...(r.branch && { branch: r.branch }),
      }))
    )
  );
  writeFileSync(
    join(targetDir, "README.md"),
    readmeHostRepo(
      name,
      withRemotes.map((r) => ({ name: r.name, github: r.github! }))
    )
  );
  writeFileSync(
    join(targetDir, ".gitignore"),
    [
      "# withctx — cached sources and internal state (wiki context/ is tracked)",
      ".ctx/sources/",
      ".ctx/costs.json",
      ".ctx/exports/",
      ".ctx/sync-state.json",
      ".env",
      "",
    ].join("\n")
  );

  console.log(chalk.green("  ✓") + ` Created ./${name}/ctx.yaml`);
  console.log(chalk.green("  ✓") + ` Created ./${name}/.github/workflows/refresh-wiki.yml`);
  console.log(chalk.green("  ✓") + ` Created ./${name}/README.md`);
  console.log(chalk.green("  ✓") + ` Created ./${name}/.gitignore`);

  // Print next-steps.
  console.log();
  console.log(chalk.bold.green("  Published!") + chalk.dim(` ${name}`));
  console.log();
  console.log(chalk.bold("  Next steps:"));
  console.log();
  console.log(`    ${chalk.cyan("1.")} Create the GitHub repo and push:`);
  console.log(`       ${chalk.bold(`cd ${name}`)}`);
  console.log(`       ${chalk.bold("git init && git add . && git commit -m 'Initial wiki'")}`);
  console.log(
    `       ${chalk.bold(`gh repo create <org>/${name} --private --source=. --push`)}`
  );
  console.log();
  console.log(`    ${chalk.cyan("2.")} Add the secrets the workflow needs:`);
  console.log(
    `       ${chalk.bold('gh secret set ANTHROPIC_API_KEY --body "$ANTHROPIC_API_KEY"')}`
  );
  console.log(
    `       ${chalk.bold('gh secret set SOURCE_REPO_TOKEN --body "$GITHUB_TOKEN"')}`
  );
  console.log(
    chalk.dim(
      "       (SOURCE_REPO_TOKEN needs read access to the source repos above)"
    )
  );
  console.log();
  console.log(
    `    ${chalk.cyan("3.")} Kick the first run: ${chalk.bold("gh workflow run refresh-wiki")}`
  );
  console.log();
  console.log(
    chalk.dim("  Teammates then just `git clone` this repo and run `ctx chat`.")
  );
  console.log();
}

// ---------------------------------------------------------------------------
// Command registration
// ---------------------------------------------------------------------------

export function registerPublishCommand(program: Command): void {
  program
    .command("publish [name]")
    .description(
      "Turn this wiki into a CI-refreshed one. Run inside a repo for in-place mode, or from a parent folder with a name for a shared wiki host repo."
    )
    .option(
      "--repo <paths...>",
      "Explicit source repo paths (host-repo mode). Absolute or relative."
    )
    .option(
      "--repos-file <path>",
      "Read source repo paths from a text file (host-repo mode)."
    )
    .option(
      "--schedule <cron>",
      "Cron schedule for the refresh workflow (default: every 6h)"
    )
    .option(
      "--force",
      "Overwrite an existing .github/workflows/refresh-wiki.yml (in-place mode)"
    )
    .option("-y, --yes", "Skip all prompts")
    .action((name: string | undefined, options: PublishOptions) => {
      const cwd = resolve(process.cwd());

      console.log();
      console.log(
        chalk.bold.cyan("  ctx publish") +
          chalk.dim(" — self-refreshing wiki in CI")
      );
      console.log();

      // Mode selection.
      if (isInPlaceMode(cwd, name)) {
        console.log(
          chalk.dim("  Detected in-place mode (current repo has ctx.yaml).")
        );
        console.log();
        publishInPlace(cwd, options);
        return;
      }

      if (!name) {
        console.error(
          chalk.red(
            "  No name provided and the current folder isn't a ctx wiki."
          )
        );
        console.error();
        console.error(chalk.dim("  Use one of:"));
        console.error(
          chalk.dim("    ctx publish <name>              ") +
            chalk.dim("create a shared wiki repo")
        );
        console.error(
          chalk.dim("    cd into a repo && ctx publish   ") +
            chalk.dim("add CI refresh to the current repo")
        );
        console.error();
        process.exit(1);
      }

      // Host-repo mode.
      console.log(
        chalk.dim(`  Host-repo mode — creating ./${name}/`)
      );
      console.log();
      publishHostRepo(cwd, name, options);
    });
}
